version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: alexblacknn/web:0.0.1
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ../init_database:/app/init_database
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - .static/redoc.yaml:/var/html/redoc/redoc.yaml
      - ./templates/redoc.html:/var/html/redoc/redoc.html
    depends_on:
      - web

volumes:
  static_value:
  media_value:
